export const ROUTES = {
  SPLASH: '/',
  LANDING: '/landing',
  WELCOME: '/welcome',
  LOGIN: '/login',
  STORE_SWITCHER: '/store-switcher',
  DASHBOARD: '/dashboard',
  CUSTOMERS: '/customers',
  PRODUCTS: '/products',
  MARKETING: '/marketing',
  INSIGHTS: '/insights',
  FORECASTING: '/forecasting',
  SENTIMENT: '/sentiment',
  COPILOT: '/copilot',
  IMPORT: '/import',
  DATA_VIEWER: '/data-viewer',
  STORES: '/stores',
  REPORTS: '/reports',
  SETTINGS: '/settings',
} as const;
